version: "2.3"
services:
  load-balancer:
    image: "nginx:stable-alpine"
    ports:
      - "3000:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  dashboard:
    build:
      context: ./dashboard
    scale: 1
    depends_on:
      - auth
    ports:
      - "5555:80"
    environment:
      - REACT_APP_AUTH_URL=/auth
    restart: always
    volumes:
      - ./dashboard/etc/nginx.conf:/etc/nginx/nginx.conf:ro
  auth:
    build:
      context: ./auth-service
    scale: 1
    restart: always
    environment:
      - NODE_ENV=dev
      - DB_HOST=mongo
    ports:
      - 9000:9000
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./auth-service/src:/home/node/app/src
  giftcard:
    build:
      context: ./gift-card
    scale: 2
    depends_on:
      - auth
    restart: always
  greeting:
    build:
      context: ./greeting
    scale: 2
    depends_on:
      - auth
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
